-- Migration 002: Unit movings table for Work Order Validator
-- Idempotent — safe to re-run against an existing database.

BEGIN;

CREATE TABLE IF NOT EXISTS unit_movings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    unit_number TEXT NOT NULL,
    moving_date DATE NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT unit_movings_unit_date_unique UNIQUE (unit_number, moving_date)
);

CREATE INDEX IF NOT EXISTS unit_movings_unit_number_idx ON unit_movings (unit_number);

COMMIT;
