-- Migration 005: Phase scope — persistent scope configuration per property.
-- Idempotent — safe to re-run.

BEGIN;

CREATE TABLE IF NOT EXISTS phase_scope (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_id BIGINT NOT NULL REFERENCES property(property_id) ON DELETE CASCADE,
    user_id BIGINT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT phase_scope_property_unique UNIQUE (property_id)
);

CREATE TABLE IF NOT EXISTS phase_scope_phase (
    phase_scope_id BIGINT NOT NULL REFERENCES phase_scope(id) ON DELETE CASCADE,
    phase_id BIGINT NOT NULL REFERENCES phase(phase_id) ON DELETE CASCADE,
    PRIMARY KEY (phase_scope_id, phase_id)
);

CREATE INDEX IF NOT EXISTS phase_scope_phase_scope_idx ON phase_scope_phase(phase_scope_id);

COMMIT;
