-- Application users for Streamlit login (DB-backed roles: admin, validator).

BEGIN;

CREATE TABLE IF NOT EXISTS app_user (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL,
    password_hash TEXT NOT NULL,
    role TEXT NOT NULL CHECK (role IN ('admin', 'validator')),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT app_user_username_lower CHECK (username = lower(trim(username))),
    CONSTRAINT app_user_username_not_blank CHECK (btrim(username) <> ''),
    CONSTRAINT app_user_username_unique UNIQUE (username)
);

DROP TRIGGER IF EXISTS app_user_set_updated_at ON app_user;
CREATE TRIGGER app_user_set_updated_at
    BEFORE UPDATE ON app_user
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE app_user IS 'Legacy Streamlit login users. username stored lower(trim). password_hash is Argon2id string.';

COMMIT;
