-- Migration 014: Append-only lifecycle_event — turnover phase / lifecycle history.
-- Phase labels align with domain.turnover_lifecycle (PRE_NOTICE … CANCELED).

CREATE TABLE IF NOT EXISTS lifecycle_event (
    lifecycle_event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_id BIGINT NOT NULL REFERENCES property(property_id) ON DELETE RESTRICT,
    turnover_id BIGINT NOT NULL,
    from_phase TEXT,
    to_phase TEXT NOT NULL,
    event_type TEXT NOT NULL DEFAULT 'PHASE_TRANSITION',
    actor TEXT NOT NULL,
    source TEXT NOT NULL,
    payload JSONB,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT lifecycle_event_turnover_fk
        FOREIGN KEY (property_id, turnover_id)
        REFERENCES turnover(property_id, turnover_id)
        ON DELETE RESTRICT,
    CONSTRAINT lifecycle_event_from_phase_valid CHECK (
        from_phase IS NULL
        OR from_phase IN (
            'PRE_NOTICE', 'ON_NOTICE', 'VACANT_NOT_READY', 'VACANT_READY',
            'OCCUPIED', 'CLOSED', 'CANCELED'
        )
    ),
    CONSTRAINT lifecycle_event_to_phase_valid CHECK (
        to_phase IN (
            'PRE_NOTICE', 'ON_NOTICE', 'VACANT_NOT_READY', 'VACANT_READY',
            'OCCUPIED', 'CLOSED', 'CANCELED'
        )
    ),
    CONSTRAINT lifecycle_event_event_type_not_blank CHECK (BTRIM(event_type) <> ''),
    CONSTRAINT lifecycle_event_actor_not_blank CHECK (BTRIM(actor) <> ''),
    CONSTRAINT lifecycle_event_source_not_blank CHECK (BTRIM(source) <> '')
);

CREATE INDEX IF NOT EXISTS lifecycle_event_turnover_occurred_idx
    ON lifecycle_event (property_id, turnover_id, occurred_at DESC);

DROP TRIGGER IF EXISTS lifecycle_event_prevent_mutation ON lifecycle_event;
CREATE TRIGGER lifecycle_event_prevent_mutation
    BEFORE UPDATE OR DELETE ON lifecycle_event
    FOR EACH ROW
    EXECUTE FUNCTION prevent_mutation();

COMMENT ON TABLE lifecycle_event IS
    'Append-only history of derived lifecycle phases per turnover; written by transition service / automation (not UI directly).';
