BEGIN;

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION prevent_mutation()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION 'Table % is append-only', TG_TABLE_NAME;
END;
$$;

CREATE TABLE property (
    property_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT property_name_not_blank CHECK (BTRIM(name) <> '')
);

CREATE TABLE phase (
    phase_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_id BIGINT NOT NULL REFERENCES property(property_id) ON DELETE RESTRICT,
    phase_code TEXT NOT NULL,
    name TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT phase_code_not_blank CHECK (BTRIM(phase_code) <> ''),
    CONSTRAINT phase_property_code_unique UNIQUE (property_id, phase_code)
);

CREATE TABLE building (
    building_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_id BIGINT NOT NULL REFERENCES property(property_id) ON DELETE RESTRICT,
    phase_id BIGINT NOT NULL REFERENCES phase(phase_id) ON DELETE RESTRICT,
    building_code TEXT NOT NULL,
    name TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT building_code_not_blank CHECK (BTRIM(building_code) <> ''),
    CONSTRAINT building_phase_code_unique UNIQUE (phase_id, building_code)
);

CREATE TABLE unit (
    unit_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_id BIGINT NOT NULL REFERENCES property(property_id) ON DELETE RESTRICT,
    phase_id BIGINT REFERENCES phase(phase_id) ON DELETE RESTRICT,
    building_id BIGINT REFERENCES building(building_id) ON DELETE RESTRICT,
    unit_code_raw TEXT NOT NULL,
    unit_code_norm TEXT NOT NULL,
    unit_identity_key TEXT NOT NULL,
    floor_plan TEXT,
    gross_sq_ft INTEGER,
    has_carpet BOOLEAN NOT NULL DEFAULT FALSE,
    has_wd_expected BOOLEAN NOT NULL DEFAULT FALSE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT unit_code_norm_not_blank CHECK (BTRIM(unit_code_norm) <> ''),
    CONSTRAINT unit_identity_key_not_blank CHECK (BTRIM(unit_identity_key) <> ''),
    CONSTRAINT unit_property_unit_code_unique UNIQUE (property_id, unit_code_norm),
    CONSTRAINT unit_property_identity_key_unique UNIQUE (property_id, unit_identity_key),
    CONSTRAINT unit_property_unit_unique UNIQUE (property_id, unit_id)
);

CREATE TABLE turnover (
    turnover_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_id BIGINT NOT NULL REFERENCES property(property_id) ON DELETE RESTRICT,
    unit_id BIGINT NOT NULL,
    move_out_date DATE NOT NULL,
    move_in_date DATE,
    report_ready_date DATE,
    available_date DATE,
    availability_status TEXT,
    scheduled_move_out_date DATE,
    confirmed_move_out_date DATE,
    legal_confirmation_source TEXT,
    legal_confirmed_at TIMESTAMPTZ,
    manual_ready_status TEXT,
    manual_ready_confirmed_at TIMESTAMPTZ,
    closed_at TIMESTAMPTZ,
    canceled_at TIMESTAMPTZ,
    cancel_reason TEXT,
    missing_moveout_count INTEGER NOT NULL DEFAULT 0,
    move_out_manual_override_at TIMESTAMPTZ,
    move_in_manual_override_at TIMESTAMPTZ,
    ready_manual_override_at TIMESTAMPTZ,
    status_manual_override_at TIMESTAMPTZ,
    wd_notified_at TIMESTAMPTZ,
    wd_installed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT turnover_unit_fk
        FOREIGN KEY (property_id, unit_id)
        REFERENCES unit(property_id, unit_id)
        ON DELETE RESTRICT,
    CONSTRAINT turnover_property_turnover_unique UNIQUE (property_id, turnover_id),
    CONSTRAINT turnover_manual_ready_status_valid CHECK (
        manual_ready_status IS NULL
        OR manual_ready_status IN ('On Notice', 'Vacant Not Ready', 'Vacant Ready')
    ),
    CONSTRAINT turnover_availability_status_not_blank CHECK (
        availability_status IS NULL OR BTRIM(availability_status) <> ''
    ),
    CONSTRAINT turnover_legal_confirmation_source_not_blank CHECK (
        legal_confirmation_source IS NULL OR BTRIM(legal_confirmation_source) <> ''
    ),
    CONSTRAINT turnover_wd_install_requires_notify CHECK (
        wd_installed_at IS NULL OR wd_notified_at IS NOT NULL
    ),
    CONSTRAINT turnover_state_exclusive CHECK (
        NOT (closed_at IS NOT NULL AND canceled_at IS NOT NULL)
    ),
    CONSTRAINT turnover_cancel_reason_requires_cancel CHECK (
        cancel_reason IS NULL OR canceled_at IS NOT NULL
    ),
    CONSTRAINT turnover_move_in_after_move_out CHECK (
        move_in_date IS NULL OR move_in_date >= move_out_date
    ),
    CONSTRAINT turnover_available_after_move_out CHECK (
        available_date IS NULL OR available_date >= move_out_date
    ),
    -- report_ready_date may precede move_out_date (unit prepped before vacancy)
    CONSTRAINT turnover_manual_ready_confirmed_requires_status CHECK (
        manual_ready_confirmed_at IS NULL OR manual_ready_status = 'Vacant Ready'
    ),
    CONSTRAINT turnover_legal_confirmed_requires_source CHECK (
        legal_confirmed_at IS NULL OR legal_confirmation_source IS NOT NULL
    )
);

CREATE UNIQUE INDEX ux_turnover_one_open
    ON turnover (unit_id)
    WHERE closed_at IS NULL AND canceled_at IS NULL;

CREATE TABLE task_template (
    template_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_id BIGINT NOT NULL REFERENCES property(property_id) ON DELETE RESTRICT,
    phase_id BIGINT NOT NULL REFERENCES phase(phase_id) ON DELETE RESTRICT,
    task_type TEXT NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    offset_days_from_move_out INTEGER NOT NULL,
    required BOOLEAN NOT NULL DEFAULT TRUE,
    blocking BOOLEAN NOT NULL DEFAULT TRUE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    skip_allowed BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT task_template_type_not_blank CHECK (BTRIM(task_type) <> ''),
    CONSTRAINT task_template_sort_order_nonnegative CHECK (sort_order >= 0),
    CONSTRAINT task_template_offset_days_valid CHECK (offset_days_from_move_out >= 1)
);

CREATE UNIQUE INDEX task_template_phase_type_active_idx
    ON task_template (phase_id, task_type)
    WHERE is_active = TRUE;

CREATE TABLE task (
    task_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_id BIGINT NOT NULL REFERENCES property(property_id) ON DELETE RESTRICT,
    turnover_id BIGINT NOT NULL,
    task_type TEXT NOT NULL,
    scheduled_date DATE,
    vendor_due_date DATE,
    execution_status TEXT NOT NULL DEFAULT 'SCHEDULED',
    vendor_completed_at TIMESTAMPTZ,
    completed_date DATE,
    required BOOLEAN NOT NULL DEFAULT TRUE,
    blocking BOOLEAN NOT NULL DEFAULT TRUE,
    skip_allowed BOOLEAN NOT NULL DEFAULT FALSE,
    blocked_reason TEXT,
    assignee TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT task_turnover_fk
        FOREIGN KEY (property_id, turnover_id)
        REFERENCES turnover(property_id, turnover_id)
        ON DELETE RESTRICT,
    CONSTRAINT task_type_not_blank CHECK (BTRIM(task_type) <> ''),
    CONSTRAINT task_execution_status_valid CHECK (
        execution_status IN ('SCHEDULED', 'IN_PROGRESS', 'COMPLETE', 'SKIPPED', 'BLOCKED')
    ),
    CONSTRAINT task_turnover_task_type_unique UNIQUE (turnover_id, task_type),
    CONSTRAINT task_property_task_unique UNIQUE (property_id, task_id),
    CONSTRAINT task_completed_requires_vendor_completed_at CHECK (
        execution_status <> 'COMPLETE' OR vendor_completed_at IS NOT NULL
    )
);

CREATE TABLE note (
    note_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_id BIGINT NOT NULL REFERENCES property(property_id) ON DELETE RESTRICT,
    turnover_id BIGINT NOT NULL,
    severity TEXT NOT NULL,
    text TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    resolved_at TIMESTAMPTZ,
    CONSTRAINT note_turnover_fk
        FOREIGN KEY (property_id, turnover_id)
        REFERENCES turnover(property_id, turnover_id)
        ON DELETE RESTRICT,
    CONSTRAINT note_text_not_blank CHECK (BTRIM(text) <> ''),
    CONSTRAINT note_severity_valid CHECK (severity IN ('INFO', 'WARNING', 'CRITICAL'))
);

CREATE TABLE risk_flag (
    risk_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_id BIGINT NOT NULL REFERENCES property(property_id) ON DELETE RESTRICT,
    turnover_id BIGINT NOT NULL,
    risk_type TEXT NOT NULL,
    severity TEXT NOT NULL,
    opened_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    resolved_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT risk_flag_turnover_fk
        FOREIGN KEY (property_id, turnover_id)
        REFERENCES turnover(property_id, turnover_id)
        ON DELETE RESTRICT,
    CONSTRAINT risk_flag_type_not_blank CHECK (BTRIM(risk_type) <> ''),
    CONSTRAINT risk_flag_severity_valid CHECK (severity IN ('INFO', 'WARNING', 'CRITICAL')),
    CONSTRAINT risk_flag_resolution_order CHECK (
        resolved_at IS NULL OR resolved_at >= opened_at
    )
);

CREATE UNIQUE INDEX risk_flag_one_open_idx
    ON risk_flag (turnover_id, risk_type)
    WHERE resolved_at IS NULL;

CREATE TABLE sla_event (
    sla_event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_id BIGINT NOT NULL REFERENCES property(property_id) ON DELETE RESTRICT,
    turnover_id BIGINT NOT NULL,
    breach_started_at TIMESTAMPTZ NOT NULL,
    breach_resolved_at TIMESTAMPTZ,
    threshold_days INTEGER NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT sla_event_turnover_fk
        FOREIGN KEY (property_id, turnover_id)
        REFERENCES turnover(property_id, turnover_id)
        ON DELETE RESTRICT,
    CONSTRAINT sla_event_threshold_positive CHECK (threshold_days > 0),
    CONSTRAINT sla_event_resolution_order CHECK (
        breach_resolved_at IS NULL OR breach_resolved_at >= breach_started_at
    )
);

CREATE UNIQUE INDEX sla_event_one_open_breach_idx
    ON sla_event (turnover_id)
    WHERE breach_resolved_at IS NULL;

CREATE TABLE lifecycle_event (
    lifecycle_event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_id BIGINT NOT NULL REFERENCES property(property_id) ON DELETE RESTRICT,
    turnover_id BIGINT NOT NULL,
    from_phase TEXT,
    to_phase TEXT NOT NULL,
    event_type TEXT NOT NULL DEFAULT 'PHASE_TRANSITION',
    actor TEXT NOT NULL,
    source TEXT NOT NULL,
    payload JSONB,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT lifecycle_event_turnover_fk
        FOREIGN KEY (property_id, turnover_id)
        REFERENCES turnover(property_id, turnover_id)
        ON DELETE RESTRICT,
    CONSTRAINT lifecycle_event_from_phase_valid CHECK (
        from_phase IS NULL
        OR from_phase IN (
            'PRE_NOTICE', 'ON_NOTICE', 'VACANT_NOT_READY', 'VACANT_READY',
            'OCCUPIED', 'CLOSED', 'CANCELED'
        )
    ),
    CONSTRAINT lifecycle_event_to_phase_valid CHECK (
        to_phase IN (
            'PRE_NOTICE', 'ON_NOTICE', 'VACANT_NOT_READY', 'VACANT_READY',
            'OCCUPIED', 'CLOSED', 'CANCELED'
        )
    ),
    CONSTRAINT lifecycle_event_event_type_not_blank CHECK (BTRIM(event_type) <> ''),
    CONSTRAINT lifecycle_event_actor_not_blank CHECK (BTRIM(actor) <> ''),
    CONSTRAINT lifecycle_event_source_not_blank CHECK (BTRIM(source) <> '')
);

CREATE INDEX lifecycle_event_turnover_occurred_idx
    ON lifecycle_event (property_id, turnover_id, occurred_at DESC);

CREATE TRIGGER lifecycle_event_prevent_mutation
    BEFORE UPDATE OR DELETE ON lifecycle_event
    FOR EACH ROW
    EXECUTE FUNCTION prevent_mutation();

CREATE TABLE audit_log (
    audit_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_id BIGINT NOT NULL REFERENCES property(property_id) ON DELETE RESTRICT,
    entity_type TEXT NOT NULL,
    entity_id BIGINT NOT NULL,
    field_name TEXT NOT NULL,
    old_value TEXT,
    new_value TEXT,
    actor TEXT NOT NULL,
    source TEXT NOT NULL,
    changed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT audit_log_entity_type_not_blank CHECK (BTRIM(entity_type) <> ''),
    CONSTRAINT audit_log_field_name_not_blank CHECK (BTRIM(field_name) <> ''),
    CONSTRAINT audit_log_actor_not_blank CHECK (BTRIM(actor) <> ''),
    CONSTRAINT audit_log_source_not_blank CHECK (BTRIM(source) <> '')
);

CREATE TABLE import_batch (
    batch_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_id BIGINT NOT NULL REFERENCES property(property_id) ON DELETE RESTRICT,
    report_type TEXT NOT NULL,
    checksum TEXT NOT NULL,
    status TEXT NOT NULL,
    record_count INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT import_batch_report_type_not_blank CHECK (BTRIM(report_type) <> ''),
    CONSTRAINT import_batch_checksum_not_blank CHECK (BTRIM(checksum) <> ''),
    CONSTRAINT import_batch_status_not_blank CHECK (BTRIM(status) <> ''),
    CONSTRAINT import_batch_record_count_nonnegative CHECK (record_count >= 0)
);

CREATE TABLE import_row (
    row_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_id BIGINT NOT NULL REFERENCES property(property_id) ON DELETE RESTRICT,
    batch_id BIGINT NOT NULL REFERENCES import_batch(batch_id) ON DELETE RESTRICT,
    unit_code_raw TEXT,
    unit_code_norm TEXT,
    move_out_date DATE,
    move_in_date DATE,
    validation_status TEXT NOT NULL,
    conflict_flag BOOLEAN NOT NULL DEFAULT FALSE,
    conflict_reason TEXT,
    raw_json JSONB NOT NULL,
    resolved_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT import_row_validation_status_valid CHECK (
        validation_status IN ('OK', 'INVALID', 'CONFLICT', 'IGNORED', 'SKIPPED_OVERRIDE')
    ),
    CONSTRAINT import_row_conflict_reason_requires_conflict CHECK (
        conflict_reason IS NULL OR conflict_flag = TRUE
    )
);

CREATE TABLE turnover_task_override (
    property_id BIGINT NOT NULL REFERENCES property(property_id) ON DELETE RESTRICT,
    turnover_id BIGINT NOT NULL,
    task_type TEXT NOT NULL,
    required_override BOOLEAN,
    blocking_override BOOLEAN,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (property_id, turnover_id, task_type),
    CONSTRAINT turnover_task_override_turnover_fk
        FOREIGN KEY (property_id, turnover_id)
        REFERENCES turnover(property_id, turnover_id)
        ON DELETE RESTRICT,
    CONSTRAINT turnover_task_override_type_not_blank CHECK (BTRIM(task_type) <> '')
);

CREATE TABLE unit_movings (
    unit_movings_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    unit_number TEXT NOT NULL,
    moving_date DATE NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT unit_movings_unit_date_unique UNIQUE (unit_number, moving_date)
);

CREATE TABLE unit_on_notice_snapshot (
    property_id BIGINT NOT NULL REFERENCES property(property_id) ON DELETE CASCADE,
    unit_id BIGINT NOT NULL,
    available_date DATE NOT NULL,
    move_in_ready_date DATE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (property_id, unit_id),
    CONSTRAINT unit_on_notice_snapshot_unit_fk
        FOREIGN KEY (property_id, unit_id)
        REFERENCES unit(property_id, unit_id)
        ON DELETE CASCADE
);

CREATE TABLE app_user (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL,
    password_hash TEXT NOT NULL,
    role TEXT NOT NULL CHECK (role IN ('admin', 'validator')),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT app_user_username_lower CHECK (username = lower(trim(username))),
    CONSTRAINT app_user_username_not_blank CHECK (btrim(username) <> ''),
    CONSTRAINT app_user_username_unique UNIQUE (username)
);

CREATE INDEX phase_property_idx ON phase (property_id);
CREATE INDEX building_phase_idx ON building (phase_id);
CREATE INDEX unit_identity_key_idx ON unit (unit_identity_key);
CREATE INDEX unit_property_active_idx ON unit (property_id, is_active);
CREATE INDEX turnover_unit_idx ON turnover (unit_id);
CREATE INDEX turnover_property_open_idx
    ON turnover (property_id, move_out_date, move_in_date)
    WHERE closed_at IS NULL AND canceled_at IS NULL;
CREATE INDEX task_turnover_idx ON task (turnover_id);
CREATE INDEX task_property_turnover_idx ON task (property_id, turnover_id);
CREATE INDEX risk_flag_turnover_idx ON risk_flag (turnover_id);
CREATE INDEX import_row_batch_idx ON import_row (batch_id);
CREATE INDEX import_batch_property_created_idx ON import_batch (property_id, created_at DESC);
CREATE INDEX unit_on_notice_snapshot_available_date_idx
    ON unit_on_notice_snapshot (property_id, available_date);
CREATE INDEX note_turnover_idx ON note (turnover_id, resolved_at);
CREATE INDEX sla_event_turnover_idx ON sla_event (turnover_id, breach_started_at);
CREATE INDEX audit_log_entity_idx ON audit_log (entity_type, entity_id, changed_at DESC);

CREATE TRIGGER property_set_updated_at
    BEFORE UPDATE ON property
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER phase_set_updated_at
    BEFORE UPDATE ON phase
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER building_set_updated_at
    BEFORE UPDATE ON building
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER unit_set_updated_at
    BEFORE UPDATE ON unit
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER turnover_set_updated_at
    BEFORE UPDATE ON turnover
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER task_template_set_updated_at
    BEFORE UPDATE ON task_template
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER task_set_updated_at
    BEFORE UPDATE ON task
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER note_set_updated_at
    BEFORE UPDATE ON note
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER risk_flag_set_updated_at
    BEFORE UPDATE ON risk_flag
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER sla_event_set_updated_at
    BEFORE UPDATE ON sla_event
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER turnover_task_override_set_updated_at
    BEFORE UPDATE ON turnover_task_override
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER import_batch_set_updated_at
    BEFORE UPDATE ON import_batch
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER import_row_set_updated_at
    BEFORE UPDATE ON import_row
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER unit_on_notice_snapshot_set_updated_at
    BEFORE UPDATE ON unit_on_notice_snapshot
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER app_user_set_updated_at
    BEFORE UPDATE ON app_user
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER audit_log_prevent_update
    BEFORE UPDATE OR DELETE ON audit_log
    FOR EACH ROW
    EXECUTE FUNCTION prevent_mutation();

COMMIT;
